server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: postgres
    password: azerty

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    ma.geo.local.school: DEBUG
    org.hibernate: ERROR