server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username:
    password:

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: create
    show-sql: true

  profiles:
    active: dev

rsa:
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkHbzFHjYxN+JIsB9aw8SmEEJhQdhovraHwUXkpJr1SM6hq9+Kdl+iMTiqn0d2MGTdwLREGPbsI+rASLq1HEZBn6adZbI1xDakx4JUTNuvjfpt8TFoI6m6mA3IRHh94lsshXEcxObJVH7coYQNRkWwEJXxXjDdEYARTHgj7r2dHHNiwShehYm1k4L5333pYfArigkL5DsOHRYuULa6AkrGIPi6g73snqJhWNKnTj20Ur+6oMkVGedRt+xWaJa/8piec4FQUJEg7rOgd5YREwQgn0PZ16HuDQ0tx2sagilU17nEW+IoVKeKNQgw5whHCkQz4RajDU8Q6Do1siHkBNCCwIDAQAB
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCQdvMUeNjE34kiwH1rDxKYQQmFB2Gi+tofBReSkmvVIzqGr34p2X6IxOKqfR3YwZN3AtEQY9uwj6sBIurUcRkGfpp1lsjXENqTHglRM26+N+m3xMWgjqbqYDchEeH3iWyyFcRzE5slUftyhhA1GRbAQlfFeMN0RgBFMeCPuvZ0cc2LBKF6FibWTgvnffelh8CuKCQvkOw4dFi5QtroCSsYg+LqDveyeomFY0qdOPbRSv7qgyRUZ51G37FZolr/ymJ5zgVBQkSDus6B3lhETBCCfQ9nXoe4NDS3HaxqCKVTXucRb4ihUp4o1CDDnCEcKRDPhFqMNTxDoOjWyIeQE0ILAgMBAAECggEAMcw/CJyLpHmlrQwLb58XetJYdLnRpzuveqfns0ez0hm9r/XImKZ3Xq/3rmtIoZJAwfJ/nJW/ggJUISUnK6n8xWdY2RXsD26o2bOt5IbFMt7VOtqigTELSpl2B3lBmnGNvWmReVWV0myLL7QU3CjU1dtIpDJ3tZn3t+J0lTcOg56+QPdX1EYjUQJbJUqVfX8iNYX48zVXU9U2Oc1BPZMixsV2pnoGP8c2rlB1+FUVWLFstBt+rvF1lCn4x7sRYR4Wq0sIB+YiQqvtbgRN/yQapLfoQbUGrkCnaJnwVk9YgPISen+AYrwLefuSgSLwqKmfNRc59oZUXR+Fjwqfo7iVyQKBgQDLT6BsnZ3IjmbotJ5TNAP+jh/hcT/2T/1i8nlqmMV+d+3rBH22VdPTetFeuXdDvEl8tGCjpGrsiKPd6e2Iyamtt4WZvx9mCSP7GlBQlcuoLQha16TsMW7ObvlqvH08sT9v2wqF/l7Wvap37cibWP3kj46gU3UbjZQz2ZqwSag+hQKBgQC15z62HiOh9B5BG5QD8rnNvoe3kuCqj1sA5JtrUG1iHAWg6dT3gKXG1EnTCoLj5Cr01uM0bgiVQY2qdqHCclQ/Bumc/AJpnV1iDTsaSJ1rdqQSuRJ0+NWtEc/1eqUiZQO4YyrVWfVUPYot9HZ6bHEr+EThZid/wiRiDi+uKKtLTwKBgALjX7ELUCmANGAL6M/fxkrAdB18wV7bZgsYzLbB8tRIGd4j0zFa6MZxUTYaRmJ080pNOa45cLdpfYJyh0hRLRLlr4UunOCTMqqnhgqPBjSeZyb7N0GPtjZCh1KH2POaxP7uyqh6o5hDW3+WpinmyryLeYg3h0tb6IYQCk2EzloNAoGAVVDaVuyX5dPrhLn8mEV15Avi97TJ7vVBx49xXcnhI8zkzu4dVuBd4H2dCoC5l01i4GcRNXwORoLygOsXP24EGXOSinCgaQzHyb9O4yr/unFwzt9Cyt4SyhO6p/YYEaOzNP4+Dscci6A5eQhZsV2/TtIo7FbPW9qg2eSxdEva230CgYB2+51o/lGkEosDfzso9CsBiPh/Rh/8kxxNf05EGGsLRuvLvJaAg4x4iGhziw2Auh5nfa9BiEjr5nLtpUhZGX/e8/7eYvYIqxPOMYX69ICuUqJgXFa5t1LXBinXu5tQIlio5bwu3/7fPbDEvc/MAaaxoJzVbqOWl6rfsQXOe8fN1A==