server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: postgres
    password: azerty

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: dev